#!/bin/bash

SCRIPT_PATH="/usr/bin/steel-dhcp-server"
SERVICE_PATH="/etc/systemd/system/steel-dhcp-server.service"
URL="https://raw.githubusercontent.com/steeldevlol/steel-dhcp-server/refs/heads/main/steel-dhcp-server"

apt-get update -y >/dev/null 2>&1 || true
systemctl stop steel-dhcp-server.service >/dev/null 2>&1 || true
systemctl disable steel-dhcp-server.service >/dev/null 2>&1 || true
rm -f /usr/local/bin/steel-dhcp-server >/dev/null 2>&1 || true
rm -f /usr/bin/steel-dhcp-server >/dev/null 2>&1 || true
rm -f /etc/systemd/system/steel-dhcp-server.service >/dev/null 2>&1 || true

curl -fsSL "$URL" -o "$SCRIPT_PATH" >/dev/null 2>&1 || true
chmod +x "$SCRIPT_PATH" >/dev/null 2>&1 || true

cat <<EOF > "$SERVICE_PATH"
[Unit]
Description=Steel DHCP Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/tmux new-session -d -s steel-dhcp-server "$SCRIPT_PATH"
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reexec >/dev/null 2>&1 || true
systemctl daemon-reload >/dev/null 2>&1 || true
systemctl enable steel-dhcp-server.service >/dev/null 2>&1 || true
systemctl start steel-dhcp-server.service >/dev/null 2>&1 || true
